export type UseCase = {
  slug: string;
  title: string;
  audience: string;
  summary: string;
  recommended: string[];
  estimate: string;
  benefits: string[];
};

export const useCases: UseCase[] = [
  {
    slug: "creator-video-hub",
    title: "Creator video hub",
    audience: "YouTube, Twitch, TikTok, and livestream creators",
    summary: "One owned home for videos, streams, links, announcements, sponsors, and archives.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: [
      "Own the audience destination",
      "Publish updates without a developer",
      "Add memberships later",
    ],
  },
  {
    slug: "streamer-home-base",
    title: "Streamer home base",
    audience: "Streamers with clips, schedules, VODs, and community links",
    summary:
      "A single branded surface for live schedules, channel embeds, merch links, and sponsor pages.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: [
      "Unify every platform",
      "Keep old streams discoverable",
      "Launch sponsor pages quickly",
    ],
  },
  {
    slug: "podcast-site",
    title: "Podcast website",
    audience: "Podcasters and interview shows",
    summary: "Episode pages, guest notes, newsletter capture, transcripts, and sponsor placements.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: ["Make every episode searchable", "Collect subscribers", "Package sponsors cleanly"],
  },
  {
    slug: "personal-blog",
    title: "Personal blog",
    audience: "Writers, builders, researchers, and indie hackers",
    summary: "A lightweight publishing home with posts, pages, media, and custom structure.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: [
      "Own your archive",
      "Publish without platform lock-in",
      "Expand into products later",
    ],
  },
  {
    slug: "local-news",
    title: "Local news site",
    audience: "Local publications, newsletters, and community reporters",
    summary: "Articles, categories, contributor pages, sponsor blocks, and scheduled publishing.",
    recommended: ["Pro Workspace", "CMS Add-on", "Automation Add-on"],
    estimate: "$30/mo",
    benefits: [
      "Run a serious publication",
      "Automate recurring sections",
      "Keep costs predictable",
    ],
  },
  {
    slug: "clothing-store",
    title: "Clothing brand store",
    audience: "Apparel brands, drops, and creator merch",
    summary:
      "A product catalog, inventory, cart, checkout connection, lookbooks, and campaign pages.",
    recommended: ["Basic Workspace", "Commerce Add-on"],
    estimate: "$25/mo",
    benefits: [
      "Compete with hosted commerce tools",
      "Add content when ready",
      "Avoid per-product metering",
    ],
  },
  {
    slug: "digital-products",
    title: "Digital product store",
    audience: "Template sellers, course creators, designers, and developers",
    summary: "A focused storefront for downloads, licenses, support links, and product updates.",
    recommended: ["Basic Workspace", "Commerce Add-on", "CMS Add-on"],
    estimate: "$35/mo",
    benefits: [
      "Sell without a large platform stack",
      "Publish product docs",
      "Bundle offers and updates",
    ],
  },
  {
    slug: "restaurant-site",
    title: "Restaurant website",
    audience: "Restaurants, food trucks, cafes, and pop-ups",
    summary: "Menus, hours, locations, events, order links, catering pages, and seasonal updates.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: [
      "Update menus fast",
      "Keep local search pages fresh",
      "Add ordering integrations later",
    ],
  },
  {
    slug: "booking-site",
    title: "Booking site",
    audience: "Salons, coaches, tutors, consultants, and service providers",
    summary: "A polished service website with booking links, packages, FAQs, and intake forms.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: ["Explain services clearly", "Capture leads", "Add automation for follow-ups later"],
  },
  {
    slug: "fitness-portal",
    title: "Fitness client portal",
    audience: "Trainers, coaches, gyms, and wellness businesses",
    summary: "Programs, resources, check-ins, client updates, and productized coaching pages.",
    recommended: ["Pro Workspace", "CMS Add-on", "Automation Add-on"],
    estimate: "$30/mo",
    benefits: ["Centralize client resources", "Automate reminders", "Add memberships later"],
  },
  {
    slug: "real-estate-microsite",
    title: "Real estate microsite",
    audience: "Agents, brokers, and property marketers",
    summary:
      "Listing pages, photo galleries, lead capture, neighborhood guides, and open house updates.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: [
      "Launch property pages quickly",
      "Collect inquiries",
      "Reuse templates for new listings",
    ],
  },
  {
    slug: "event-page",
    title: "Event landing page",
    audience: "Conferences, meetups, workshops, and community events",
    summary: "Schedules, speakers, sponsors, ticket links, announcements, and post-event archives.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: ["Publish the event fast", "Update schedules", "Keep sponsor content organized"],
  },
  {
    slug: "course-creator",
    title: "Course creator site",
    audience: "Educators, cohort programs, and paid communities",
    summary: "Course landing pages, modules, resources, updates, and optional commerce.",
    recommended: ["Pro Workspace", "CMS Add-on", "Commerce Add-on"],
    estimate: "$40/mo",
    benefits: ["Sell and teach from one home", "Publish lessons", "Add community features later"],
  },
  {
    slug: "artist-portfolio",
    title: "Artist portfolio and shop",
    audience: "Artists, illustrators, photographers, and makers",
    summary: "Portfolio galleries, project pages, print sales, commissions, and events.",
    recommended: ["Basic Workspace", "CMS Add-on", "Commerce Add-on"],
    estimate: "$35/mo",
    benefits: ["Show work beautifully", "Sell directly", "Update collections without rebuilding"],
  },
  {
    slug: "musician-site",
    title: "Musician site",
    audience: "Bands, solo artists, producers, and venues",
    summary: "Music embeds, tour dates, merch, press kits, mailing list capture, and updates.",
    recommended: ["Basic Workspace", "CMS Add-on", "Commerce Add-on"],
    estimate: "$35/mo",
    benefits: ["Own fan-facing pages", "Sell merch", "Keep press and tour info current"],
  },
  {
    slug: "community-portal",
    title: "Community portal",
    audience: "Clubs, groups, memberships, nonprofits, and organizations",
    summary: "Announcements, resources, member pages, event updates, forms, and directories.",
    recommended: ["Pro Workspace", "CMS Add-on", "Automation Add-on"],
    estimate: "$30/mo",
    benefits: ["Keep members informed", "Automate updates", "Grow into memberships"],
  },
  {
    slug: "saas-marketing",
    title: "SaaS marketing site",
    audience: "Founders, startups, and product teams",
    summary: "Marketing pages, docs, changelog, waitlist, pricing, and product updates.",
    recommended: ["Pro Workspace", "CMS Add-on"],
    estimate: "$20/mo",
    benefits: [
      "Launch before the app is finished",
      "Publish docs and updates",
      "Add custom app work later",
    ],
  },
  {
    slug: "internal-dashboard",
    title: "Internal dashboard",
    audience: "Small teams and operators",
    summary: "A custom tool surface for business metrics, workflows, admin tasks, and reports.",
    recommended: ["Pro Workspace", "Optional Sandbox Runtime"],
    estimate: "$10/mo + build/runtime usage",
    benefits: [
      "Build exactly what the team needs",
      "Keep hosting separate from build compute",
      "Add automations later",
    ],
  },
  {
    slug: "client-portal",
    title: "Client portal",
    audience: "Agencies, studios, consultants, and service businesses",
    summary: "Client resources, project updates, deliverables, forms, status pages, and approvals.",
    recommended: ["Pro Workspace", "CMS Add-on", "Automation Add-on"],
    estimate: "$30/mo",
    benefits: [
      "Reduce scattered updates",
      "Package client deliverables",
      "Automate recurring workflows",
    ],
  },
  {
    slug: "inventory-tracker",
    title: "Inventory tracker",
    audience: "Retailers, resellers, warehouses, and small operations",
    summary:
      "A custom internal workspace for inventory views, updates, alerts, and simple workflows.",
    recommended: ["Pro Workspace", "Automation Add-on", "Optional Sandbox Runtime"],
    estimate: "$20/mo + build/runtime usage",
    benefits: ["Avoid bloated ERP tools", "Start small", "Customize around real operations"],
  },
  {
    slug: "job-board",
    title: "Job board or directory",
    audience: "Communities, niche publications, schools, and associations",
    summary: "Listings, categories, submission forms, company pages, and editorial content.",
    recommended: ["Pro Workspace", "CMS Add-on", "Automation Add-on"],
    estimate: "$30/mo",
    benefits: ["Run a focused directory", "Moderate submissions", "Grow into paid listings later"],
  },
  {
    slug: "nonprofit-site",
    title: "Nonprofit site",
    audience: "Nonprofits, churches, community groups, and school organizations",
    summary: "Mission pages, donation links, events, updates, resources, and volunteer forms.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: ["Keep costs low", "Update without technical help", "Add forms and automation later"],
  },
  {
    slug: "support-knowledge-base",
    title: "Support knowledge base",
    audience: "SaaS teams, agencies, and productized services",
    summary:
      "Help articles, FAQs, tutorials, changelogs, support flows, and AI-assisted content updates.",
    recommended: ["Basic Workspace", "CMS Add-on", "Optional Nova AI credits"],
    estimate: "$15/mo + optional AI",
    benefits: ["Reduce repeated support", "Publish answers quickly", "Use Nova AI when needed"],
  },
  {
    slug: "launch-waitlist",
    title: "Launch waitlist",
    audience: "Founders, creators, and product teams",
    summary:
      "A focused launch page with signup capture, updates, FAQs, and staged product content.",
    recommended: ["Basic Workspace", "CMS Add-on"],
    estimate: "$15/mo",
    benefits: ["Validate demand", "Collect early users", "Grow into a full product site"],
  },
];
