#!/bin/sh
set -eu

usage() {
  cat <<'EOF'
Usage: install-nova-openrc.sh [options]

Installs and enables the Nova OpenRC service stack on Alpine.

Options:
  --repo-root PATH         Nova monorepo root. Default: current working directory
  --setup-user USER        User that owns and runs the Nova services
  --setup-group GROUP      Group for the Nova services. Default: user's primary group
  --public-host HOST       Host or IP used for PUBLIC_SITE_URL/BETTER_AUTH_URL
  --surreal-mode MODE      SurrealDB backend: docker or native. Default: docker
  --no-enable              Install service files without enabling them in OpenRC
  --no-start               Install and enable, but do not restart/start services now
  --help                   Show this help text
EOF
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root." >&2
    exit 1
  fi
}

ensure_dir() {
  if [ ! -d "$1" ]; then
    echo "Required directory not found: $1" >&2
    exit 1
  fi
}

primary_group_for_user() {
  id -gn "$1"
}

home_for_user() {
  getent passwd "$1" | cut -d: -f6
}

find_node_bin() {
  setup_home="$1"
  latest_node=""
  set +e
  latest_node=$(ls -1d "${setup_home}"/.vite-plus/js_runtime/node/*/bin/node 2>/dev/null | tail -n 1)
  set -e
  if [ -n "$latest_node" ]; then
    printf '%s\n' "$latest_node"
    return
  fi
  command -v node
}

SETUP_USER=""
SETUP_GROUP=""
PUBLIC_HOST=""
SURREAL_MODE="docker"
ENABLE_SERVICES=1
START_SERVICES=1
REPO_ROOT="$(pwd)"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo-root)
      REPO_ROOT="$2"
      shift 2
      ;;
    --setup-user)
      SETUP_USER="$2"
      shift 2
      ;;
    --setup-group)
      SETUP_GROUP="$2"
      shift 2
      ;;
    --public-host)
      PUBLIC_HOST="$2"
      shift 2
      ;;
    --surreal-mode)
      SURREAL_MODE="$2"
      shift 2
      ;;
    --no-enable)
      ENABLE_SERVICES=0
      shift
      ;;
    --no-start)
      START_SERVICES=0
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_root

case "$SURREAL_MODE" in
  docker|native) ;;
  *)
    echo "Invalid --surreal-mode: $SURREAL_MODE" >&2
    exit 1
    ;;
esac

REPO_ROOT="$(cd "$REPO_ROOT" && pwd)"
NOVA_CLOUD_DIR="${REPO_ROOT}/apps/nova-cloud"
NOVA_RUNTIME_CONTROL_DIR="${REPO_ROOT}/apps/nova-runtime-control"
NOVA_SURREAL_DATA_DIR="${NOVA_CLOUD_DIR}/surreal/data"

ensure_dir "$REPO_ROOT"
ensure_dir "$NOVA_CLOUD_DIR"
ensure_dir "$NOVA_RUNTIME_CONTROL_DIR"

if [ -z "$SETUP_USER" ]; then
  if [ -d "${NOVA_CLOUD_DIR}/surreal" ]; then
    SETUP_USER="$(stat -c '%U' "${NOVA_CLOUD_DIR}/surreal")"
  else
    SETUP_USER="$(stat -c '%U' "${NOVA_CLOUD_DIR}")"
  fi
fi

if ! getent passwd "$SETUP_USER" >/dev/null 2>&1; then
  echo "Setup user does not exist: $SETUP_USER" >&2
  exit 1
fi

if [ -z "$SETUP_GROUP" ]; then
  SETUP_GROUP="$(primary_group_for_user "$SETUP_USER")"
fi

SETUP_HOME="$(home_for_user "$SETUP_USER")"
if [ -z "$SETUP_HOME" ]; then
  echo "Could not resolve home directory for user: $SETUP_USER" >&2
  exit 1
fi

VP_BIN="${SETUP_HOME}/.vite-plus/bin/vp"
NODE_BIN="$(find_node_bin "$SETUP_HOME")"

if [ ! -x "$VP_BIN" ]; then
  echo "Vite+ binary not found: $VP_BIN" >&2
  exit 1
fi

if [ ! -x "$NODE_BIN" ]; then
  echo "Node binary not found for setup user: $SETUP_USER" >&2
  exit 1
fi

if [ -z "$PUBLIC_HOST" ]; then
  PUBLIC_HOST="$(hostname -f 2>/dev/null || hostname)"
fi

PUBLIC_DEV_URL="http://${PUBLIC_HOST}:8105"
PUBLIC_PROD_URL="http://${PUBLIC_HOST}:8106"

mkdir -p /etc/conf.d

cat > /etc/conf.d/nova-cloud <<EOF
# Shared Nova Cloud service settings.
# Generated by tools/alpine-server/install-nova-openrc.sh
: "\${NOVA_ROOT:=${REPO_ROOT}}"
: "\${NOVA_CLOUD_DIR:=\${NOVA_ROOT}/apps/nova-cloud}"
: "\${NOVA_RUNTIME_CONTROL_DIR:=\${NOVA_ROOT}/apps/nova-runtime-control}"
: "\${NOVA_SURREAL_DATA_DIR:=\${NOVA_CLOUD_DIR}/surreal/data}"
: "\${NOVA_SETUP_USER:=${SETUP_USER}}"
: "\${NOVA_SETUP_GROUP:=${SETUP_GROUP}}"
: "\${NOVA_SETUP_HOME:=${SETUP_HOME}}"
: "\${NOVA_VP_BIN:=${VP_BIN}}"
: "\${NOVA_NODE_BIN:=${NODE_BIN}}"
: "\${NOVA_PUBLIC_DEV_URL:=${PUBLIC_DEV_URL}}"
: "\${NOVA_PUBLIC_PROD_URL:=${PUBLIC_PROD_URL}}"
: "\${NOVA_SURREAL_MODE:=${SURREAL_MODE}}"
EOF
chmod 0644 /etc/conf.d/nova-cloud

cat > /etc/init.d/nova-cloud-dev <<'EOF'
#!/sbin/openrc-run
[ -r /etc/conf.d/nova-cloud ] && . /etc/conf.d/nova-cloud

name="Nova Cloud Dev"
description="Nova Cloud Vite dev server on port 8105"
supervisor=supervise-daemon
command="${NOVA_VP_BIN}"
command_args="dev --host 0.0.0.0 --port 8105"
command_user="${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}"
directory="${NOVA_CLOUD_DIR}"
output_log="/var/log/nova-cloud-dev.log"
error_log="/var/log/nova-cloud-dev.err"
respawn_delay=2
respawn_max=0
export HOME="${NOVA_SETUP_HOME}"
export PATH="/usr/libexec/rc/bin:/sbin:/bin:/usr/sbin:/usr/bin:${NOVA_SETUP_HOME}/.vite-plus/bin:$(dirname "${NOVA_NODE_BIN}"):/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export PUBLIC_SITE_URL="${PUBLIC_SITE_URL:-${NOVA_PUBLIC_DEV_URL}}"
export BETTER_AUTH_URL="${BETTER_AUTH_URL:-${NOVA_PUBLIC_DEV_URL}}"
export NOVA_APP_URL="${NOVA_APP_URL:-${NOVA_PUBLIC_DEV_URL}}"

depend() {
  need net nova-surrealdb nova-runtime-control
}

start_pre() {
  checkpath -f -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 0644 "${output_log}"
  checkpath -f -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 0644 "${error_log}"
}
EOF

cat > /etc/init.d/nova-cloud-prod <<'EOF'
#!/sbin/openrc-run
[ -r /etc/conf.d/nova-cloud ] && . /etc/conf.d/nova-cloud

name="Nova Cloud Production Preview"
description="Nova Cloud production build preview on port 8106"
supervisor=supervise-daemon
command="${NOVA_NODE_BIN}"
command_args="build/index.js"
command_user="${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}"
directory="${NOVA_CLOUD_DIR}"
output_log="/var/log/nova-cloud-prod.log"
error_log="/var/log/nova-cloud-prod.err"
respawn_delay=2
respawn_max=0
export HOME="${NOVA_SETUP_HOME}"
export PATH="/usr/libexec/rc/bin:/sbin:/bin:/usr/sbin:/usr/bin:${NOVA_SETUP_HOME}/.vite-plus/bin:$(dirname "${NOVA_NODE_BIN}"):/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export HOST="0.0.0.0"
export PORT="8106"
export PUBLIC_SITE_URL="${PUBLIC_SITE_URL:-${NOVA_PUBLIC_PROD_URL}}"
export BETTER_AUTH_URL="${BETTER_AUTH_URL:-${NOVA_PUBLIC_PROD_URL}}"
export NOVA_APP_URL="${NOVA_APP_URL:-${NOVA_PUBLIC_PROD_URL}}"

depend() {
  need net nova-surrealdb nova-runtime-control
}

start_pre() {
  checkpath -f -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 0644 "${output_log}"
  checkpath -f -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 0644 "${error_log}"
  if [ ! -f "${NOVA_CLOUD_DIR}/build/index.js" ]; then
    ebegin "Building Nova Cloud before production preview"
    su "${NOVA_SETUP_USER}" -s /bin/sh -c "cd '${NOVA_CLOUD_DIR}' && PATH='${NOVA_SETUP_HOME}/.vite-plus/bin:$(dirname "${NOVA_NODE_BIN}"):$PATH' PUBLIC_SITE_URL='${NOVA_PUBLIC_PROD_URL}' BETTER_AUTH_URL='${NOVA_PUBLIC_PROD_URL}' NOVA_APP_URL='${NOVA_PUBLIC_PROD_URL}' '${NOVA_VP_BIN}' build"
    eend $?
  fi
}
EOF

cat > /etc/init.d/nova-runtime-control <<'EOF'
#!/sbin/openrc-run
[ -r /etc/conf.d/nova-cloud ] && . /etc/conf.d/nova-cloud

name="Nova Runtime Control"
description="Nova K3s runtime control plane API"
supervisor=supervise-daemon
command="${NOVA_NODE_BIN}"
command_args="--experimental-strip-types src/index.ts"
command_user="${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}"
directory="${NOVA_RUNTIME_CONTROL_DIR}"
output_log="/var/log/nova-runtime-control.log"
error_log="/var/log/nova-runtime-control.err"
respawn_delay=2
respawn_max=0
export HOME="${NOVA_SETUP_HOME}"
export PATH="/usr/libexec/rc/bin:/sbin:/bin:/usr/sbin:/usr/bin:${NOVA_SETUP_HOME}/.vite-plus/bin:$(dirname "${NOVA_NODE_BIN}"):/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

depend() {
  need net
  after k3s
}

start_pre() {
  checkpath -f -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 0644 "${output_log}"
  checkpath -f -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 0644 "${error_log}"
}
EOF

cat > /etc/init.d/nova-surrealdb <<'EOF'
#!/sbin/openrc-run
[ -r /etc/conf.d/nova-cloud ] && . /etc/conf.d/nova-cloud

name="Nova SurrealDB"
description="Nova Cloud SurrealDB service"
supervisor=supervise-daemon
output_log="/var/log/nova-surrealdb.log"
error_log="/var/log/nova-surrealdb.err"
respawn_delay=2
respawn_max=0

setup_uid() {
  id -u "${NOVA_SETUP_USER}"
}

setup_gid() {
  id -g "${NOVA_SETUP_USER}"
}

depend() {
  need net
  after localmount
  if [ "${NOVA_SURREAL_MODE}" = "docker" ]; then
    need docker
  fi
}

start_pre() {
  checkpath -d -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 2775 "${NOVA_CLOUD_DIR}/surreal"
  checkpath -d -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 2775 "${NOVA_SURREAL_DATA_DIR}"
  checkpath -f -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 0644 "${output_log}"
  checkpath -f -o "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" -m 0644 "${error_log}"
  chown -R "${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}" "${NOVA_CLOUD_DIR}/surreal"
  rm -f "${NOVA_SURREAL_DATA_DIR}/LOCK"
}

start() {
  if [ "${NOVA_SURREAL_MODE}" = "native" ]; then
    command="${NOVA_CLOUD_DIR}/scripts/start-surreal.sh"
    command_user="${NOVA_SETUP_USER}:${NOVA_SETUP_GROUP}"
    directory="${NOVA_CLOUD_DIR}"
    export HOME="${NOVA_SETUP_HOME}"
    export PATH="/usr/libexec/rc/bin:/sbin:/bin:/usr/sbin:/usr/bin:${NOVA_SETUP_HOME}/.vite-plus/bin:$(dirname "${NOVA_NODE_BIN}"):/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    export SURREAL_DATA_DIR="${NOVA_SURREAL_DATA_DIR}"
    default_start
    return $?
  fi

  ebegin "Starting Nova SurrealDB Docker container"
  docker rm -f nova-surrealdb >/dev/null 2>&1 || true
  docker run -d \
    --name nova-surrealdb \
    --user "$(setup_uid):$(setup_gid)" \
    --restart unless-stopped \
    -p 127.0.0.1:8000:8000 \
    -v "${NOVA_SURREAL_DATA_DIR}:/data" \
    -w /data \
    surrealdb/surrealdb:v3.0.5 \
    start --bind 0.0.0.0:8000 --username root --password root --no-banner surrealkv://. >/dev/null
  eend $?
}

stop() {
  if [ "${NOVA_SURREAL_MODE}" = "native" ]; then
    default_stop
    return $?
  fi
  ebegin "Stopping Nova SurrealDB Docker container"
  docker rm -f nova-surrealdb >/dev/null 2>&1 || true
  eend $?
}

status() {
  if [ "${NOVA_SURREAL_MODE}" = "native" ]; then
    default_status
    return $?
  fi
  docker ps --filter name=^/nova-surrealdb$ --format '{{.Names}} {{.Status}}'
}
EOF

chmod 0755 \
  /etc/init.d/nova-cloud-dev \
  /etc/init.d/nova-cloud-prod \
  /etc/init.d/nova-runtime-control \
  /etc/init.d/nova-surrealdb

if [ "$ENABLE_SERVICES" -eq 1 ]; then
  if [ "$SURREAL_MODE" = "docker" ]; then
    rc-update add docker default >/dev/null 2>&1 || true
  fi
  rc-update add nova-surrealdb default >/dev/null 2>&1 || true
  rc-update add nova-runtime-control default >/dev/null 2>&1 || true
  rc-update add nova-cloud-dev default >/dev/null 2>&1 || true
  rc-update add nova-cloud-prod default >/dev/null 2>&1 || true
fi

if [ "$START_SERVICES" -eq 1 ]; then
  rc-service nova-cloud-prod stop >/dev/null 2>&1 || true
  rc-service nova-cloud-dev stop >/dev/null 2>&1 || true
  rc-service nova-runtime-control stop >/dev/null 2>&1 || true
  rc-service nova-surrealdb stop >/dev/null 2>&1 || true

  rc-service nova-surrealdb start
  rc-service nova-runtime-control start
  rc-service nova-cloud-dev start
  rc-service nova-cloud-prod start
fi

cat <<EOF
Installed Nova OpenRC stack.
  repo root:      ${REPO_ROOT}
  setup user:     ${SETUP_USER}
  setup group:    ${SETUP_GROUP}
  public host:    ${PUBLIC_HOST}
  surreal mode:   ${SURREAL_MODE}
  enabled:        ${ENABLE_SERVICES}
  started:        ${START_SERVICES}
EOF
