packages:
  - apps/*
  - packages/*
  - tools/*
allowBuilds:
  "@blackbelt-technology/pi-agent-dashboard": true
  "@blackbelt-technology/pi-dashboard-server": true
  "@tailwindcss/oxide": true
  "@zvec/zvec": true
  esbuild: true
  node-pty: true
  nx: true
  protobufjs: true
  puppeteer: true
  sharp: true
  workerd: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
