apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deployment-default-deny
  namespace: nova-deployments
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deployment-edge-and-dns
  namespace: nova-deployments
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: nova-release-runtime
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              nova.dlxstudios.com/edge-connector: "true"
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
