apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-runtime
  namespace: nova-deployments
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-runtime-no-api
  namespace: nova-deployments
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-runtime-no-api
  namespace: nova-deployments
subjects:
  - kind: ServiceAccount
    name: release-runtime
    namespace: nova-deployments
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-runtime-no-api
