apiVersion: v1
kind: Service
metadata:
  name: nova-canvas
  namespace: nova-cloud
  labels:
    app.kubernetes.io/name: nova-canvas
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nova-canvas
  ports:
    - name: http
      port: 10002
      targetPort: http
