apiVersion: v1
kind: Service
metadata:
  name: nova-website
  namespace: nova-cloud
  labels:
    app.kubernetes.io/name: nova-website
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nova-website
  ports:
    - name: http
      port: 10001
      targetPort: http
