apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nova-surrealdb-data
  namespace: nova-cloud
  labels:
    app.kubernetes.io/name: nova-surrealdb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
