apiVersion: v1
kind: Secret
metadata:
  name: nova-surrealdb-app-env
  namespace: nova-cloud
type: Opaque
stringData:
  SURREALDB_URL: http://nova-surrealdb.nova-cloud.svc.cluster.local:8000/rpc
  SURREALDB_NAMESPACE: main
  SURREALDB_DATABASE: main
  SURREALDB_USERNAME: root
  SURREALDB_PASSWORD: change-me
