[package]
name = "edge-proxy"
description = "Reverse proxy with middleware pipeline"
version.workspace = true
edition.workspace = true

[dependencies]
edge-store = { path = "../edge-store" }
edge-config = { path = "../edge-config" }

axum = { workspace = true }
hyper = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
dashmap = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
governor = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bytes = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
flate2 = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
