#!/bin/sh
set -eu

usage() {
  cat <<'EOF'
Usage: install-nova-surreal-systemd.sh [options]

Installs a systemd unit for Nova Cloud SurrealDB on Debian/systemd hosts.

Options:
  --repo-root PATH         Nova monorepo root. Default: current working directory
  --setup-user USER        User that owns and runs the Nova services
  --setup-group GROUP      Group for the Nova services. Default: user's primary group
  --surreal-mode MODE      SurrealDB backend: native or docker. Default: native
  --no-enable              Install service files without enabling them in systemd
  --no-start               Install and enable, but do not restart/start the service now
  --help                   Show this help text
EOF
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root." >&2
    exit 1
  fi
}

ensure_dir() {
  if [ ! -d "$1" ]; then
    echo "Required directory not found: $1" >&2
    exit 1
  fi
}

primary_group_for_user() {
  id -gn "$1"
}

home_for_user() {
  getent passwd "$1" | cut -d: -f6
}

find_surreal_bin() {
  setup_home="$1"

  if [ -n "${SURREAL_BIN:-}" ] && [ -x "${SURREAL_BIN}" ]; then
    printf '%s\n' "${SURREAL_BIN}"
    return
  fi

  if [ -x "${setup_home}/.surrealdb/surreal" ]; then
    printf '%s\n' "${setup_home}/.surrealdb/surreal"
    return
  fi

  if command -v surreal >/dev/null 2>&1; then
    command -v surreal
    return
  fi

  echo "Could not find a usable surreal binary." >&2
  exit 1
}

SETUP_USER=""
SETUP_GROUP=""
SURREAL_MODE="native"
ENABLE_SERVICE=1
START_SERVICE=1
REPO_ROOT="$(pwd)"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo-root)
      REPO_ROOT="$2"
      shift 2
      ;;
    --setup-user)
      SETUP_USER="$2"
      shift 2
      ;;
    --setup-group)
      SETUP_GROUP="$2"
      shift 2
      ;;
    --surreal-mode)
      SURREAL_MODE="$2"
      shift 2
      ;;
    --no-enable)
      ENABLE_SERVICE=0
      shift
      ;;
    --no-start)
      START_SERVICE=0
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_root

case "$SURREAL_MODE" in
  native|docker) ;;
  *)
    echo "Invalid --surreal-mode: $SURREAL_MODE" >&2
    exit 1
    ;;
esac

REPO_ROOT="$(cd "$REPO_ROOT" && pwd)"
NOVA_CLOUD_DIR="${REPO_ROOT}/apps/nova-cloud"
NOVA_SURREAL_DIR="${NOVA_CLOUD_DIR}/surreal"
NOVA_SURREAL_DATA_DIR="${NOVA_SURREAL_DIR}/data"
START_SCRIPT="${NOVA_CLOUD_DIR}/scripts/start-surreal.sh"

ensure_dir "$REPO_ROOT"
ensure_dir "$NOVA_CLOUD_DIR"
ensure_dir "$NOVA_SURREAL_DIR"

if [ -z "$SETUP_USER" ]; then
  SETUP_USER="$(stat -c '%U' "$NOVA_SURREAL_DIR")"
fi

if ! getent passwd "$SETUP_USER" >/dev/null 2>&1; then
  echo "Setup user does not exist: $SETUP_USER" >&2
  exit 1
fi

if [ -z "$SETUP_GROUP" ]; then
  SETUP_GROUP="$(primary_group_for_user "$SETUP_USER")"
fi

SETUP_HOME="$(home_for_user "$SETUP_USER")"
if [ -z "$SETUP_HOME" ]; then
  echo "Could not resolve home directory for user: $SETUP_USER" >&2
  exit 1
fi

SURREAL_BIN_PATH="$(find_surreal_bin "$SETUP_HOME")"

if [ ! -x "$START_SCRIPT" ]; then
  echo "Expected start script not found or not executable: $START_SCRIPT" >&2
  exit 1
fi

mkdir -p /etc/default
cat > /etc/default/nova-cloud <<EOF
# Shared Nova Cloud service settings.
# Generated by tools/debian/install-nova-surreal-systemd.sh
NOVA_ROOT="${REPO_ROOT}"
NOVA_CLOUD_DIR="${NOVA_CLOUD_DIR}"
NOVA_SURREAL_DIR="${NOVA_SURREAL_DIR}"
NOVA_SURREAL_DATA_DIR="${NOVA_SURREAL_DATA_DIR}"
NOVA_SETUP_USER="${SETUP_USER}"
NOVA_SETUP_GROUP="${SETUP_GROUP}"
NOVA_SETUP_HOME="${SETUP_HOME}"
NOVA_SURREAL_MODE="${SURREAL_MODE}"
SURREAL_BIN="${SURREAL_BIN_PATH}"
SURREAL_DATA_DIR="${NOVA_SURREAL_DATA_DIR}"
SURREAL_BIND_ADDR="127.0.0.1:8000"
SURREAL_USERNAME="root"
SURREAL_PASSWORD="root"
EOF
chmod 0644 /etc/default/nova-cloud

cat > /etc/systemd/system/nova-surrealdb.service <<EOF
[Unit]
Description=Nova Cloud SurrealDB service
After=network-online.target local-fs.target
Wants=network-online.target
ConditionPathExists=/etc/default/nova-cloud

[Service]
Type=simple
EnvironmentFile=/etc/default/nova-cloud
WorkingDirectory=${NOVA_CLOUD_DIR}
User=${SETUP_USER}
Group=${SETUP_GROUP}
UMask=0002
ExecStartPre=/usr/bin/install -d -o ${SETUP_USER} -g ${SETUP_GROUP} -m 2775 ${NOVA_SURREAL_DIR}
ExecStartPre=/usr/bin/install -d -o ${SETUP_USER} -g ${SETUP_GROUP} -m 2775 ${NOVA_SURREAL_DATA_DIR}
ExecStartPre=/usr/bin/chown -R ${SETUP_USER}:${SETUP_GROUP} ${NOVA_SURREAL_DIR}
ExecStartPre=/usr/bin/rm -f ${NOVA_SURREAL_DATA_DIR}/LOCK
ExecStart=${NOVA_CLOUD_DIR}/scripts/start-surreal.sh
Restart=always
RestartSec=2
NoNewPrivileges=true
PrivateTmp=true
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF
chmod 0644 /etc/systemd/system/nova-surrealdb.service

systemctl daemon-reload

if [ "$ENABLE_SERVICE" -eq 1 ]; then
  systemctl enable nova-surrealdb.service >/dev/null
fi

if [ "$START_SERVICE" -eq 1 ]; then
  systemctl stop nova-surrealdb.service >/dev/null 2>&1 || true
  systemctl start nova-surrealdb.service
fi

cat <<EOF
Installed Nova systemd SurrealDB service.
  repo root:      ${REPO_ROOT}
  setup user:     ${SETUP_USER}
  setup group:    ${SETUP_GROUP}
  surreal mode:   ${SURREAL_MODE}
  surreal binary: ${SURREAL_BIN_PATH}
  enabled:        ${ENABLE_SERVICE}
  started:        ${START_SERVICE}
EOF
