import { WORKSPACE_PATH, ensureSandboxForRuntime } from "./sandbox";
import { upsertArtifact } from "./surreal-artifacts";
import { upsertPrimaryForStudio } from "./surreal-runtime-processes";
import {
  buildWorkspaceRuntimeContract,
  getWorkspaceForStudio,
  listDeploymentsForWorkspace,
  markWorkspaceDeploymentStatus,
  normalizeWorkspaceBuildCommand,
} from "./surreal-workspaces";

const BLOG_INDEX_JSON = JSON.stringify(
  [
    {
      slug: "hello-world",
      title: "Hello World",
      summary: "A starter post generated by Nova inside the Studio sandbox.",
      publishedAt: "2026-05-01",
    },
  ],
  null,
  2,
);

const BLOG_MARKDOWN = `# Hello World

This is the first blog post generated by Nova.

- The source project lives in the Studio sandbox
- The content lives under the workspace content folder
- The production build is written to the workspace build folder

This is the first contract path for deployable React workspaces.
`;

const BLOG_APP_TSX = `import { useEffect, useMemo, useState } from 'react';
import './index.css';

type PostIndexEntry = {
  slug: string;
  title: string;
  summary: string;
  publishedAt: string;
};

export default function App() {
  const [posts, setPosts] = useState<PostIndexEntry[]>([]);
  const [selectedSlug, setSelectedSlug] = useState<string | null>(null);
  const [markdown, setMarkdown] = useState<string>('');
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');

  useEffect(() => {
    let active = true;
    async function loadIndex() {
      try {
        const res = await fetch('/content/index.json');
        if (!res.ok) throw new Error('Failed to load post index');
        const data = (await res.json()) as PostIndexEntry[];
        if (!active) return;
        setPosts(data);
        setSelectedSlug(data[0]?.slug ?? null);
      } catch (error) {
        console.error(error);
        if (active) setStatus('error');
      }
    }
    void loadIndex();
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    if (!selectedSlug) return;
    let active = true;
    async function loadPost() {
      try {
        setStatus('loading');
        const res = await fetch('/content/posts/' + selectedSlug + '.md');
        if (!res.ok) throw new Error('Failed to load post content');
        const text = await res.text();
        if (!active) return;
        setMarkdown(text);
        setStatus('ready');
      } catch (error) {
        console.error(error);
        if (active) setStatus('error');
      }
    }
    void loadPost();
    return () => {
      active = false;
    };
  }, [selectedSlug]);

  const selectedPost = useMemo(
    () => posts.find((post) => post.slug === selectedSlug) ?? posts[0] ?? null,
    [posts, selectedSlug],
  );

  return (
    <div className="shell">
      <aside className="sidebar">
        <div>
          <p className="eyebrow">Nova Workspace</p>
          <h1>React Blog</h1>
          <p className="lede">
            Built in the sandbox with Vite+ and published from the workspace build folder.
          </p>
        </div>
        <nav className="posts">
          {posts.map((post) => (
            <button
              key={post.slug}
              className={post.slug === selectedPost?.slug ? 'post active' : 'post'}
              onClick={() => setSelectedSlug(post.slug)}
            >
              <span>{post.title}</span>
              <small>{post.publishedAt}</small>
            </button>
          ))}
        </nav>
      </aside>
      <main className="content">
        {selectedPost ? (
          <>
            <header>
              <p className="eyebrow">Published {selectedPost.publishedAt}</p>
              <h2>{selectedPost.title}</h2>
              <p className="summary">{selectedPost.summary}</p>
            </header>
            {status === 'error' ? (
              <div className="empty">Failed to load content.</div>
            ) : status === 'loading' ? (
              <div className="empty">Loading content...</div>
            ) : (
              <pre className="markdown">{markdown}</pre>
            )}
          </>
        ) : (
          <div className="empty">No posts yet.</div>
        )}
      </main>
    </div>
  );
}
`;

const BLOG_INDEX_CSS = `:root {
  font-family: Inter, system-ui, sans-serif;
  color: #e5eef7;
  background: #0f1720;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at top left, rgba(14, 165, 233, 0.16), transparent 28%),
    radial-gradient(circle at top right, rgba(34, 197, 94, 0.12), transparent 24%),
    #0f1720;
}

button {
  font: inherit;
}

.shell {
  display: grid;
  grid-template-columns: 320px minmax(0, 1fr);
  min-height: 100vh;
}

.sidebar {
  border-right: 1px solid rgba(148, 163, 184, 0.18);
  background: rgba(15, 23, 32, 0.88);
  padding: 32px 24px;
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.eyebrow {
  margin: 0 0 12px;
  text-transform: uppercase;
  letter-spacing: 0.18em;
  font-size: 11px;
  color: #7dd3fc;
}

.sidebar h1,
.content h2 {
  margin: 0;
  font-size: 32px;
  line-height: 1.1;
}

.lede,
.summary {
  color: #94a3b8;
  line-height: 1.7;
}

.posts {
  display: grid;
  gap: 12px;
}

.post {
  width: 100%;
  text-align: left;
  border: 1px solid rgba(148, 163, 184, 0.18);
  background: rgba(15, 23, 32, 0.72);
  color: inherit;
  border-radius: 14px;
  padding: 14px 16px;
  display: grid;
  gap: 4px;
  cursor: pointer;
}

.post small {
  color: #94a3b8;
}

.post.active {
  border-color: rgba(56, 189, 248, 0.38);
  background: rgba(14, 165, 233, 0.12);
}

.content {
  padding: 40px;
}

.markdown {
  margin-top: 28px;
  white-space: pre-wrap;
  line-height: 1.8;
  font-family: inherit;
  color: #dbe7f3;
  background: rgba(15, 23, 32, 0.66);
  border: 1px solid rgba(148, 163, 184, 0.18);
  border-radius: 18px;
  padding: 24px;
}

.empty {
  margin-top: 28px;
  border: 1px dashed rgba(148, 163, 184, 0.28);
  border-radius: 18px;
  padding: 24px;
  color: #94a3b8;
}

@media (max-width: 900px) {
  .shell {
    grid-template-columns: 1fr;
  }

  .sidebar {
    border-right: 0;
    border-bottom: 1px solid rgba(148, 163, 184, 0.18);
  }

  .content {
    padding: 24px;
  }
}
`;

function patchWorkspaceViteConfig(source: string) {
  if (source.includes("allowedHosts")) {
    return source;
  }

  const insertion = `  server: {\n    allowedHosts: [".e2b.app", "localhost", "127.0.0.1"],\n  },\n  preview: {\n    allowedHosts: [".e2b.app", "localhost", "127.0.0.1"],\n  },\n`;

  if (source.includes("plugins: [react()],\n});")) {
    return source.replace("plugins: [react()],\n});", `plugins: [react()],\n${insertion}});`);
  }

  return source;
}

function workspaceAbsolutePath(relativePath: string) {
  return `${WORKSPACE_PATH}/${relativePath}`.replace(/\/+/g, "/");
}

async function fileExists(
  sandbox: Awaited<ReturnType<typeof ensureSandboxForRuntime>>,
  path: string,
) {
  try {
    await sandbox.files.read(path);
    return true;
  } catch {
    return false;
  }
}

async function writeBlogWorkspaceStarter(
  sandbox: Awaited<ReturnType<typeof ensureSandboxForRuntime>>,
  workspace: Awaited<ReturnType<typeof getWorkspaceForStudio>>,
) {
  if (!workspace) {
    throw new Error("Workspace not found");
  }

  const sourceRoot = workspaceAbsolutePath(workspace.sourcePath).replace(/\/$/, "");
  const contentRoot = workspaceAbsolutePath(workspace.contentPath).replace(/\/$/, "");
  const postsRoot = `${contentRoot}/posts`;

  await sandbox.files.makeDir(contentRoot);
  await sandbox.files.makeDir(postsRoot);
  await sandbox.files.write(`${contentRoot}/index.json`, BLOG_INDEX_JSON);
  await sandbox.files.write(`${postsRoot}/hello-world.md`, BLOG_MARKDOWN);
  await sandbox.files.write(`${sourceRoot}/src/App.tsx`, BLOG_APP_TSX);
  await sandbox.files.write(`${sourceRoot}/src/index.css`, BLOG_INDEX_CSS);

  const viteConfigPath = `${sourceRoot}/vite.config.js`;
  if (await fileExists(sandbox, viteConfigPath)) {
    const current = await sandbox.files.read(viteConfigPath);
    await sandbox.files.write(viteConfigPath, patchWorkspaceViteConfig(current));
  }
}

export async function provisionWorkspaceInSandbox(input: {
  event: Parameters<typeof ensureSandboxForRuntime>[0]["event"];
  userId: string;
  studioId: string;
  workspaceId: string;
}) {
  const workspace = await getWorkspaceForStudio(input.userId, input.studioId, input.workspaceId);
  if (!workspace) {
    throw new Error("Workspace not found");
  }

  const [deployment] = await listDeploymentsForWorkspace(
    input.userId,
    input.studioId,
    workspace._id,
  );
  if (!deployment) {
    throw new Error("Workspace deployment not found");
  }

  const sandbox = await ensureSandboxForRuntime({
    event: input.event,
    userId: input.userId,
    studioId: input.studioId,
  });

  const buildCommand = normalizeWorkspaceBuildCommand(
    workspace.buildCommand,
    workspace.sourcePath.replace(/source\/?$/, "source").replace(/\/$/, ""),
  );
  const normalizedWorkspace =
    buildCommand === workspace.buildCommand ? workspace : { ...workspace, buildCommand };

  await markWorkspaceDeploymentStatus({
    userId: input.userId,
    studioId: input.studioId,
    workspaceId: workspace._id,
    deploymentId: deployment._id,
    workspaceStatus: "building",
    deploymentStatus: "building",
    metadata: {
      startedAt: Date.now(),
      stage: "scaffold",
    },
  });

  const packageJsonPath = `${workspaceAbsolutePath(workspace.sourcePath).replace(/\/$/, "")}/package.json`;
  const alreadyScaffolded = await fileExists(sandbox, packageJsonPath);

  let scaffoldResult: { stdout: string; stderr: string; exitCode: number } | null = null;
  if (!alreadyScaffolded) {
    scaffoldResult = await sandbox.commands.run(workspace.scaffoldCommand, {
      cwd: WORKSPACE_PATH,
      timeoutMs: 240000,
    });
    if (scaffoldResult.exitCode !== 0) {
      await markWorkspaceDeploymentStatus({
        userId: input.userId,
        studioId: input.studioId,
        workspaceId: workspace._id,
        deploymentId: deployment._id,
        workspaceStatus: "failed",
        deploymentStatus: "failed",
        metadata: {
          stage: "scaffold",
          stdout: scaffoldResult.stdout,
          stderr: scaffoldResult.stderr,
          exitCode: scaffoldResult.exitCode,
        },
      });
      throw new Error(scaffoldResult.stderr || "Workspace scaffold failed");
    }
  }

  await writeBlogWorkspaceStarter(sandbox, workspace);

  const buildResult = await sandbox.commands.run(buildCommand, {
    cwd: WORKSPACE_PATH,
    timeoutMs: 240000,
  });
  if (buildResult.exitCode !== 0) {
    await markWorkspaceDeploymentStatus({
      userId: input.userId,
      studioId: input.studioId,
      workspaceId: workspace._id,
      deploymentId: deployment._id,
      workspaceStatus: "failed",
      deploymentStatus: "failed",
      metadata: {
        stage: "build",
        stdout: buildResult.stdout,
        stderr: buildResult.stderr,
        exitCode: buildResult.exitCode,
      },
    });
    throw new Error(buildResult.stderr || "Workspace build failed");
  }

  const marked = await markWorkspaceDeploymentStatus({
    userId: input.userId,
    studioId: input.studioId,
    workspaceId: workspace._id,
    deploymentId: deployment._id,
    workspaceStatus: "published",
    deploymentStatus: "active",
    activated: true,
    metadata: {
      stage: "published",
      stdout: buildResult.stdout,
      stderr: buildResult.stderr,
      buildPath: deployment.artifactPath,
    },
  });

  const runtimeContract = buildWorkspaceRuntimeContract(normalizedWorkspace, marked.deployment);

  const artifact = await upsertArtifact({
    userId: input.userId,
    studioId: input.studioId,
    kind: "deploy-output",
    key: `workspace-build-${workspace._id}`,
    title: `${workspace.name} build`,
    status: "ready",
    path: deployment.artifactPath,
    source: "workspace-build",
    metadata: {
      workspaceId: workspace._id,
      deploymentId: deployment._id,
      framework: workspace.framework,
      templateKind: workspace.templateKind,
      buildCommand,
      runCommand: workspace.runCommand,
      runtimeKind: workspace.runtimeKind,
      lifecycleMode: workspace.lifecycleMode,
      healthCheckPath: workspace.healthCheckPath ?? null,
      publicHost: workspace.publicHost ?? workspace.defaultHost ?? null,
      statePath: workspace.statePath,
      outputDir: deployment.outputDir,
    },
  });

  return {
    workspace: marked.workspace,
    deployment: marked.deployment,
    artifact,
    runtimeContract,
    scaffoldResult,
    buildResult,
  };
}

export async function startWorkspacePreview(input: {
  event: Parameters<typeof ensureSandboxForRuntime>[0]["event"];
  userId: string;
  studioId: string;
  workspaceId: string;
  port?: number;
}) {
  const workspace = await getWorkspaceForStudio(input.userId, input.studioId, input.workspaceId);
  if (!workspace) {
    throw new Error("Workspace not found");
  }

  const sandbox = await ensureSandboxForRuntime({
    event: input.event,
    userId: input.userId,
    studioId: input.studioId,
  });

  const port = input.port ?? 4173;
  const runCommand = workspace.runCommand || workspace.serveCommand;
  const handle = await sandbox.commands.run(runCommand, {
    cwd: WORKSPACE_PATH,
    background: true,
    timeoutMs: 60000,
    envs: {
      PORT: String(port),
    },
  });

  const previewUrl = `https://${sandbox.getHost(port)}`;
  const process = await upsertPrimaryForStudio(input.userId, input.studioId, {
    sandboxId: sandbox.sandboxId,
    workspaceId: workspace._id,
    label: `${workspace.name} Preview`,
    command: runCommand,
    cwd: workspace.sourcePath,
    pid: handle.pid,
    port,
    previewUrl,
    status: "running",
    logSummary: `Serving ${workspace.name} from ${workspace.buildPath}`,
    runtimeKind: workspace.runtimeKind,
    lifecycleMode: workspace.lifecycleMode,
    runCommand,
    healthCheckPath: workspace.healthCheckPath ?? "/",
    publicHost: workspace.publicHost ?? workspace.defaultHost ?? null,
    statePath: workspace.statePath,
    runtimeImage: workspace.runtimeImage ?? null,
  });

  return {
    workspace,
    process,
    previewUrl,
    pid: handle.pid,
  };
}
