import { ensureK3sRuntime } from "./k3s-runtime";
import {
  callRuntimeControl,
  getRuntimeControlStatus,
  runtimeControlStudioId,
  runtimePreviewServiceHost,
  startRuntimeControlPreview,
  stopRuntimeControlPreview,
} from "./nova-runtime-control";
import { upsertArtifact } from "./surreal-artifacts";
import { upsertPrimaryForStudio } from "./surreal-runtime-processes";
import {
  buildWorkspaceRuntimeContract,
  getWorkspaceForStudio,
  listDeploymentsForWorkspace,
  markWorkspaceDeploymentStatus,
} from "./surreal-workspaces";

const BLOG_INDEX_JSON = JSON.stringify(
  [
    {
      slug: "hello-world",
      title: "Hello World",
      summary: "A starter post generated by Nova inside the Studio sandbox.",
      publishedAt: "2026-05-01",
    },
  ],
  null,
  2,
);

const BLOG_MARKDOWN = `# Hello World

This is the first blog post generated by Nova.

- The source project lives in the Studio sandbox
- The content lives under the workspace content folder
- The production build is written to the workspace build folder

This is the first contract path for deployable React workspaces.
`;

const BLOG_APP_TSX = `import { useEffect, useMemo, useState } from 'react';
import './index.css';

type PostIndexEntry = {
  slug: string;
  title: string;
  summary: string;
  publishedAt: string;
};

export default function App() {
  const [posts, setPosts] = useState<PostIndexEntry[]>([]);
  const [selectedSlug, setSelectedSlug] = useState<string | null>(null);
  const [markdown, setMarkdown] = useState<string>('');
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');

  useEffect(() => {
    let active = true;
    async function loadIndex() {
      try {
        const res = await fetch('/content/index.json');
        if (!res.ok) throw new Error('Failed to load post index');
        const data = (await res.json()) as PostIndexEntry[];
        if (!active) return;
        setPosts(data);
        setSelectedSlug(data[0]?.slug ?? null);
      } catch (error) {
        console.error(error);
        if (active) setStatus('error');
      }
    }
    void loadIndex();
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    if (!selectedSlug) return;
    let active = true;
    async function loadPost() {
      try {
        setStatus('loading');
        const res = await fetch('/content/posts/' + selectedSlug + '.md');
        if (!res.ok) throw new Error('Failed to load post content');
        const text = await res.text();
        if (!active) return;
        setMarkdown(text);
        setStatus('ready');
      } catch (error) {
        console.error(error);
        if (active) setStatus('error');
      }
    }
    void loadPost();
    return () => {
      active = false;
    };
  }, [selectedSlug]);

  const selectedPost = useMemo(
    () => posts.find((post) => post.slug === selectedSlug) ?? posts[0] ?? null,
    [posts, selectedSlug],
  );

  return (
    <div className="shell">
      <aside className="sidebar">
        <div>
          <p className="eyebrow">Nova Workspace</p>
          <h1>React Blog</h1>
          <p className="lede">
            Built in the sandbox with Vite+ and published from the workspace build folder.
          </p>
        </div>
        <nav className="posts">
          {posts.map((post) => (
            <button
              key={post.slug}
              className={post.slug === selectedPost?.slug ? 'post active' : 'post'}
              onClick={() => setSelectedSlug(post.slug)}
            >
              <span>{post.title}</span>
              <small>{post.publishedAt}</small>
            </button>
          ))}
        </nav>
      </aside>
      <main className="content">
        {selectedPost ? (
          <>
            <header>
              <p className="eyebrow">Published {selectedPost.publishedAt}</p>
              <h2>{selectedPost.title}</h2>
              <p className="summary">{selectedPost.summary}</p>
            </header>
            {status === 'error' ? (
              <div className="empty">Failed to load content.</div>
            ) : status === 'loading' ? (
              <div className="empty">Loading content...</div>
            ) : (
              <pre className="markdown">{markdown}</pre>
            )}
          </>
        ) : (
          <div className="empty">No posts yet.</div>
        )}
      </main>
    </div>
  );
}
`;

const BLOG_INDEX_CSS = `:root {
  font-family: Inter, system-ui, sans-serif;
  color: #e5eef7;
  background: #0f1720;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  min-height: 100vh;
  background:
    radial-gradient(circle at top left, rgba(14, 165, 233, 0.16), transparent 28%),
    radial-gradient(circle at top right, rgba(34, 197, 94, 0.12), transparent 24%),
    #0f1720;
}

button {
  font: inherit;
}

.shell {
  display: grid;
  grid-template-columns: 320px minmax(0, 1fr);
  min-height: 100vh;
}

.sidebar {
  border-right: 1px solid rgba(148, 163, 184, 0.18);
  background: rgba(15, 23, 32, 0.88);
  padding: 32px 24px;
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.eyebrow {
  margin: 0 0 12px;
  text-transform: uppercase;
  letter-spacing: 0.18em;
  font-size: 11px;
  color: #7dd3fc;
}

.sidebar h1,
.content h2 {
  margin: 0;
  font-size: 32px;
  line-height: 1.1;
}

.lede,
.summary {
  color: #94a3b8;
  line-height: 1.7;
}

.posts {
  display: grid;
  gap: 12px;
}

.post {
  width: 100%;
  text-align: left;
  border: 1px solid rgba(148, 163, 184, 0.18);
  background: rgba(15, 23, 32, 0.72);
  color: inherit;
  border-radius: 14px;
  padding: 14px 16px;
  display: grid;
  gap: 4px;
  cursor: pointer;
}

.post small {
  color: #94a3b8;
}

.post.active {
  border-color: rgba(56, 189, 248, 0.38);
  background: rgba(14, 165, 233, 0.12);
}

.content {
  padding: 40px;
}

.markdown {
  margin-top: 28px;
  white-space: pre-wrap;
  line-height: 1.8;
  font-family: inherit;
  color: #dbe7f3;
  background: rgba(15, 23, 32, 0.66);
  border: 1px solid rgba(148, 163, 184, 0.18);
  border-radius: 18px;
  padding: 24px;
}

.empty {
  margin-top: 28px;
  border: 1px dashed rgba(148, 163, 184, 0.28);
  border-radius: 18px;
  padding: 24px;
  color: #94a3b8;
}

@media (max-width: 900px) {
  .shell {
    grid-template-columns: 1fr;
  }

  .sidebar {
    border-right: 0;
    border-bottom: 1px solid rgba(148, 163, 184, 0.18);
  }

  .content {
    padding: 24px;
  }
}
`;

async function waitForRuntimePreviewReady(controlStudioId: string) {
  for (let attempt = 0; attempt < 30; attempt += 1) {
    const status = await getRuntimeControlStatus(controlStudioId).catch(() => null);
    const podsOutput =
      status &&
      typeof status === "object" &&
      "result" in status &&
      typeof status.result?.pods === "string"
        ? status.result.pods
        : "";
    if (/Running/i.test(podsOutput)) return;
    await new Promise((resolve) => setTimeout(resolve, 1_000));
  }
  throw new Error("Timed out waiting for runtime preview pod to become ready");
}

function patchWorkspaceViteConfig(source: string) {
  if (source.includes("allowedHosts")) {
    return source;
  }

  const insertion = `  server: {\n    allowedHosts: [".e2b.app", "localhost", "127.0.0.1"],\n  },\n  preview: {\n    allowedHosts: [".e2b.app", "localhost", "127.0.0.1"],\n  },\n`;

  if (source.includes("plugins: [react()],\n});")) {
    return source.replace("plugins: [react()],\n});", `plugins: [react()],\n${insertion}});`);
  }

  return source;
}

async function fileExists(runtime: Awaited<ReturnType<typeof ensureK3sRuntime>>, path: string) {
  try {
    await runtime.files.read(path);
    return true;
  } catch {
    return false;
  }
}

async function writeBlogWorkspaceStarter(
  runtime: Awaited<ReturnType<typeof ensureK3sRuntime>>,
  workspace: Awaited<ReturnType<typeof getWorkspaceForStudio>>,
) {
  if (!workspace) {
    throw new Error("Workspace not found");
  }

  const sourceRoot = runtime.workspacePath(workspace.sourcePath).replace(/\/$/, "");
  const buildRoot = runtime.workspacePath(workspace.buildPath).replace(/\/$/, "");
  const contentRoot = runtime.workspacePath(workspace.contentPath).replace(/\/$/, "");
  const postsRoot = `${contentRoot}/posts`;
  const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${workspace.name}</title>
    <style>
      :root {
        color-scheme: dark;
        font-family: Inter, system-ui, sans-serif;
        background: #0f1720;
        color: #e5eef7;
      }
      * { box-sizing: border-box; }
      body {
        margin: 0;
        min-height: 100vh;
        background:
          radial-gradient(circle at top left, rgba(14, 165, 233, 0.16), transparent 28%),
          radial-gradient(circle at top right, rgba(34, 197, 94, 0.12), transparent 24%),
          #0f1720;
      }
      .shell {
        max-width: 960px;
        margin: 0 auto;
        padding: 56px 24px 72px;
      }
      .eyebrow {
        margin: 0 0 12px;
        text-transform: uppercase;
        letter-spacing: 0.18em;
        font-size: 11px;
        color: #7dd3fc;
      }
      h1 {
        margin: 0;
        font-size: 42px;
        line-height: 1.05;
      }
      .lede, .summary {
        color: #94a3b8;
        line-height: 1.8;
      }
      .panel {
        margin-top: 28px;
        border: 1px solid rgba(148, 163, 184, 0.18);
        border-radius: 18px;
        background: rgba(15, 23, 32, 0.72);
        padding: 24px;
      }
      pre {
        margin: 0;
        white-space: pre-wrap;
        font: inherit;
        line-height: 1.8;
      }
    </style>
  </head>
  <body>
    <main class="shell">
      <p class="eyebrow">Nova Workspace Runtime</p>
      <h1>${workspace.name}</h1>
      <p class="lede">Served from the k3s runtime preview service without the legacy E2B path.</p>
      <section class="panel">
        <p class="eyebrow">Published from</p>
        <p class="summary">${workspace.buildPath}</p>
      </section>
      <section class="panel">
        <p class="eyebrow">Hello World</p>
        <pre>${BLOG_MARKDOWN}</pre>
      </section>
    </main>
  </body>
</html>
`;

  await runtime.files.makeDir(sourceRoot);
  await runtime.files.makeDir(buildRoot);
  await runtime.files.makeDir(contentRoot);
  await runtime.files.makeDir(postsRoot);
  await runtime.files.write(`${contentRoot}/index.json`, BLOG_INDEX_JSON);
  await runtime.files.write(`${postsRoot}/hello-world.md`, BLOG_MARKDOWN);
  await runtime.files.write(`${sourceRoot}/src/App.tsx`, BLOG_APP_TSX);
  await runtime.files.write(`${sourceRoot}/src/index.css`, BLOG_INDEX_CSS);
  await runtime.files.write(`${buildRoot}/index.html`, html);

  const viteConfigPath = `${sourceRoot}/vite.config.js`;
  if (await fileExists(runtime, viteConfigPath)) {
    const current = await runtime.files.read(viteConfigPath);
    await runtime.files.write(viteConfigPath, patchWorkspaceViteConfig(current));
  }
}

export async function provisionWorkspaceInSandbox(input: {
  event: Parameters<typeof ensureK3sRuntime>[0]["event"];
  userId: string;
  studioId: string;
  workspaceId: string;
}) {
  const workspace = await getWorkspaceForStudio(input.userId, input.studioId, input.workspaceId);
  if (!workspace) {
    throw new Error("Workspace not found");
  }

  const [deployment] = await listDeploymentsForWorkspace(
    input.userId,
    input.studioId,
    workspace._id,
  );
  if (!deployment) {
    throw new Error("Workspace deployment not found");
  }

  const runtime = await ensureK3sRuntime({
    event: input.event,
    userId: input.userId,
    studioId: input.studioId,
  });

  await markWorkspaceDeploymentStatus({
    userId: input.userId,
    studioId: input.studioId,
    workspaceId: workspace._id,
    deploymentId: deployment._id,
    workspaceStatus: "building",
    deploymentStatus: "building",
    metadata: {
      startedAt: Date.now(),
      stage: "prepare-runtime",
    },
  });

  await writeBlogWorkspaceStarter(runtime, workspace);
  const buildResult = {
    stdout: "Prepared static workspace output in k3s runtime.",
    stderr: "",
    exitCode: 0,
  };

  const marked = await markWorkspaceDeploymentStatus({
    userId: input.userId,
    studioId: input.studioId,
    workspaceId: workspace._id,
    deploymentId: deployment._id,
    workspaceStatus: "published",
    deploymentStatus: "active",
    activated: true,
    metadata: {
      stage: "published",
      stdout: buildResult.stdout,
      stderr: buildResult.stderr,
      buildPath: deployment.artifactPath,
      runtimeBackend: "k3s",
    },
  });

  const runtimeContract = buildWorkspaceRuntimeContract(workspace, marked.deployment);

  const artifact = await upsertArtifact({
    userId: input.userId,
    studioId: input.studioId,
    kind: "deploy-output",
    key: `workspace-build-${workspace._id}`,
    title: `${workspace.name} build`,
    status: "ready",
    path: deployment.artifactPath,
    source: "workspace-build",
    metadata: {
      workspaceId: workspace._id,
      deploymentId: deployment._id,
      framework: workspace.framework,
      templateKind: workspace.templateKind,
      buildCommand: workspace.buildCommand,
      runCommand: workspace.runCommand,
      runtimeKind: workspace.runtimeKind,
      lifecycleMode: workspace.lifecycleMode,
      healthCheckPath: workspace.healthCheckPath ?? null,
      publicHost: workspace.publicHost ?? workspace.defaultHost ?? null,
      statePath: workspace.statePath,
      outputDir: deployment.outputDir,
    },
  });

  return {
    workspace: marked.workspace,
    deployment: marked.deployment,
    artifact,
    runtimeContract,
    scaffoldResult: null,
    buildResult,
  };
}

export async function startWorkspacePreview(input: {
  event: Parameters<typeof ensureK3sRuntime>[0]["event"];
  userId: string;
  studioId: string;
  workspaceId: string;
  port?: number;
}) {
  const workspace = await getWorkspaceForStudio(input.userId, input.studioId, input.workspaceId);
  if (!workspace) {
    throw new Error("Workspace not found");
  }

  const port = input.port ?? 4173;
  const controlStudioId = runtimeControlStudioId(input.userId, input.studioId);
  const status = await getRuntimeControlStatus(controlStudioId).catch(() => null);
  const podsOutput =
    status &&
    typeof status === "object" &&
    "result" in status &&
    typeof status.result?.pods === "string"
      ? status.result.pods
      : "";
  if (!/Running/i.test(podsOutput)) {
    await callRuntimeControl(controlStudioId, {
      action: "start",
      systemPackages: ["git"],
    });
    await waitForRuntimePreviewReady(controlStudioId);
  }

  await stopRuntimeControlPreview(controlStudioId, { port }).catch(() => {});
  const previewStart = await startRuntimeControlPreview(controlStudioId, {
    rootPath: workspace.buildPath,
    port,
  });
  if (!previewStart.result.success) {
    throw new Error("Failed to start runtime preview server");
  }

  const previewUrl = `http://${runtimePreviewServiceHost(controlStudioId, port)}`;
  const runCommand = `nova-runtime-preview ${workspace.buildPath} --port ${port}`;
  const process = await upsertPrimaryForStudio(input.userId, input.studioId, {
    sandboxId: controlStudioId,
    workspaceId: workspace._id,
    label: `${workspace.name} Preview`,
    command: runCommand,
    cwd: workspace.buildPath,
    pid: port,
    port,
    previewUrl,
    status: "running",
    logSummary: `Serving ${workspace.name} from ${workspace.buildPath}`,
    runtimeKind: workspace.runtimeKind,
    lifecycleMode: workspace.lifecycleMode,
    runCommand,
    healthCheckPath: workspace.healthCheckPath ?? "/",
    publicHost: workspace.publicHost ?? workspace.defaultHost ?? null,
    statePath: workspace.statePath,
    runtimeImage: workspace.runtimeImage ?? null,
  });

  return {
    workspace,
    process,
    previewUrl,
    pid: port,
  };
}
